apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: padmasahu
  profile:
    displayName: padmaSahu
    email: padma@thoughtworks.com
    picture:
spec:
  memberOf: [thoughtworks, awesome-pet]