apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tw-org
  description: A collection of all Backstage user and group entities
spec:
  targets:
    - ./groups/awesome-project.yaml
    - ./groups/tw.yaml
    - ./users/users.yaml
type: url
  target: https://github.com/backstage-workshop/backstage-users/blob/master/thoughtworks/org.yaml
  rules:
    - allow: [ User, Group ]